# include all R packages in your project
library(stargazer)
library(testthat)
library(glmnet)
library(pls)
library(ggplot2)
sink("../../session-info.txt", append = TRUE)
cat("Session Information\n\n")
print(sessionInfo())
sink()