---
output: pdf_document
---


## Introduction

When working with a dataset populated with both quantitative and qualitative variables, we must dummy out categorical variables to allow for the use of qualitative data in a linear model. We then want mean center and standardize our variables, meaning that each variable will have mean zero and standard deviation 1. We do this if our variables are set on a wide range of scales (i.e. Income recorded in the thousands, whereas Gender is represented as a binary 0 or 1) and this technique allows all predictors to be used in the model and none are overshadowed. While one typically fits the model $Y \approx \beta_0 + \beta_1X_1 + \beta_2X_2 + ... + \beta_pX_p + \epsilon$ using least squares, we would like to look at extending this model to apply to non-linear, but still additive relationships. In particular, we will look at shrinkage methods and dimension reduction techniques to fit the data. Shrinkage methods involve fitting a model using all _p_ predictors. However to reduce both bias and variance, the estimated coefficients are shrunken towards zero relative to the least squares estimate. In effect, we are sacrificing unbiasdness to make a greater reduction in the variance component. Given we have too many predictor variables relative to the number of observations, we can use a shrinkage method to determine which predictor variables are significant. Dimension reduction techniques involve reducing the number of predictor variables in estimating a response. This is accomplished by projecting the _p_ predictor into an _M_-dimensional subspace with _M < p_. _M_ different _linear combinations_ of the variables are then computed, then the projections are used as predictors to fit a linear regression model by least squares. The results from these regression methods are then compared by mean standard error to choose the most accurate model to fit the data. This process will be illustrated in the following sections using the [Credit](http://www-bcf.usc.edu/~gareth/ISL/Credit.csv) dataset presented in Chapter 6 of Linear Regression in "An Introduction to Statistical Learning."

